FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base

# Expose ports
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet restore "src/CityCode.MandateSystem.WorkerService/CityCode.MandateSystem.WorkerService.csproj"

COPY . .
RUN dotnet build "src/CityCode.MandateSystem.WorkerService/CityCode.MandateSystem.WorkerService.csproj" -c Release -o /app/build

FROM build AS publish

# Publish the application
RUN dotnet publish "src/CityCode.MandateSystem.WorkerService/CityCode.MandateSystem.WorkerService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app

# Copy the published app from build stage
COPY --from=publish /app/publish .

# Set the entrypoint to the script
ENTRYPOINT dotnet CityCode.MandateSystem.WorkerService.dll
