@KeyRails.BankingApi_Host = http://localhost:5092

### KeyRails.BankingApi health check
GET {{KeyRails.BankingApi_Host}}/health

### Get KeyRails.BankingApi todo items
GET {{KeyRails.BankingApi_Host}}/todo/GetTodoItemsWithPagination?ListId=1&PageNumber=1&PageSize=10
Accept: application/json

### Create a KeyRails.BankingApi todo item
POST {{KeyRails.BankingApi_Host}}/todo/CreateTodoItem
Content-Type: application/json

{
  "listId": 1,
  "title": "KeyRails.BankingApi sample todo item"
}
