name: Automatic Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR"]
    types:
      - completed
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set owner to lowercase
        id: string
        run: echo "owner_lc=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Deploy Latest to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            IMAGE_NAME="ghcr.io/${{ steps.string.outputs.owner_lc }}/mandateapi:dev-latest"
            
            echo "--- Logging in to GHCR ---"
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            
            echo "--- Pulling latest image: $IMAGE_NAME ---"
            docker pull $IMAGE_NAME
            
            echo "--- Stopping and removing old container ---"
            docker stop mandatefe-container || true
            docker rm mandatefe-container || true
            
            echo "--- Starting new container ---"
            docker run -d --name mandateapidev-container --restart=unless-stopped -p 9001:8080 $IMAGE_NAME
